// CYBÖRG II: FRIHETENS SÖNER — in-engine cutscenes. Schema: docs/STORY_SCHEMA.md.
// Validate with: node tools/story/validate.mjs
//
// Beat keys: shot, act, line { who, text, inner? }, hold, sfx, music, text.
// - `line.inner: true` marks inner monologue (voice-over, no lip movement,
//   italic subtitle). Only used for henrik and atta.
// - `line.who` may be an actor id (on stage or heard off-screen, e.g. over the
//   phone or radio) or a voice without a body: `linnea` (Åtta's radio),
//   `glitch` (Samordnaren in Kall's broken voice), `news` (TV/radio news
//   anchor), `choir` (the lucia choir singing).
// - `text` is an on-screen caption (place and time), shown over the beat.
// - `hold` is the beat length in seconds when there is no line.
//
// Order: prolog_home follows COMICS.prolog. ferry_sink is followed by
// COMICS.interlude and then sim2_intro. river_sara_live or river_sara_dies
// (killed anyone?) plays after the Järnjätten boss, then river_archive, then
// COMICS.ending (or its lethal last page), then epilog_church and the credits.

export const CUTSCENES = {
  // ---------------------------------------------------------------- PROLOG
  prolog_home: {
    scene: 'home',
    actors: ['henrik', 'maja', 'elsa'],
    beats: [
      { shot: 'establish', hold: 4, sfx: 'wind_gust_1', music: 'music_title2', text: 'KÅLLTORP, GÖTEBORG. 12 DECEMBER 2047' },
      { shot: 'wide', line: { who: 'henrik', inner: true, text: 'Kålltorp. Vi flyttade hit i våras. Maja ville inte bo kvar där den andra hade stått i fönstret.' } },
      { shot: 'medium:henrik', act: ['henrik:pose:kneel'], line: { who: 'henrik', inner: true, text: 'Julbelysningen. Maja säger att jag köpte den på Kvibergs marknad i fjol. Jag tror henne. Det är lättare.' } },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'Tre lampor är döda. Man vrider på dem en i taget tills någon ger upp. Jag var polis i tjugo år.' } },
      { shot: 'wide', act: ['elsa:walk:mark_a', 'elsa:pose:sing'], line: { who: 'elsa', text: 'Pappa! Lyssna nu. Jag kan hela.' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Du gamla, du fria, du fjällhöga nord, du tysta, du glädjerika sköna!' } },
      { shot: 'two:henrik,elsa', act: ['henrik:pose:idle', 'elsa:pose:idle'], line: { who: 'elsa', text: 'Fröken säger att det stod friska från början. Du gamla, du friska. Sen ändrade han det.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Varför då?' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Det vet ingen. Jag tycker att friska är finare. Då gäller det dig också.' } },
      { shot: 'medium:maja', act: ['maja:pose:sit'], line: { who: 'maja', text: 'Elsa, stäng av ljusen i kronan. Batterierna ska räcka till i morgon.' } },
      { shot: 'insert:screen', line: { who: 'news', text: 'I morgon klockan sju inviger Folkrådet Karlatornet, stadens nya hjärta. Luciatåget från Haga skola går först.' } },
      { shot: 'insert:screen', line: { who: 'news', text: 'Något arkiv finns inte, säger Folkrådets talesperson. Det är ett rykte som sprids av extremister.' } },
      { shot: 'two:maja,henrik', line: { who: 'maja', text: 'Vi tittar på teve i morgon, som alla andra. Du ska inte dit och stå och vakta henne.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Jag har ingenting att göra i ett torn.' } },
      { shot: 'close:maja', line: { who: 'maja', text: 'Det sa du förra året också.' } },
      { shot: 'track:henrik', act: ['henrik:walk:mark_b'], sfx: 'codec_ring2', line: { who: 'astrom', text: 'Henrik, förlåt att jag ringer hem. Något kommer in över Kattegatt i natt, med nattfärjan från Frederikshavn.' } },
      { shot: 'close:henrik', line: { who: 'astrom', text: 'En last utan fraktsedel. Folkrådet vill inte höra talas om det. De har invigning.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Varför jag?' } },
      { shot: 'close:henrik', line: { who: 'astrom', text: 'För att du inte finns i något register. Och för att din dotter står i det där tornet i morgon.' } },
      { shot: 'ots:henrik>maja', act: ['maja:walk:mark_c'], line: { who: 'maja', text: 'Vem var det?' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Doktorn. En kontroll.' } },
      { shot: 'close:maja', line: { who: 'maja', text: 'Var hemma före lucia.' } },
      { shot: 'two:maja,henrik', line: { who: 'henrik', text: 'Jag lovar.' } },
      { shot: 'high:henrik', hold: 1, line: { who: 'henrik', inner: true, text: 'Jag har lovat saker förut, säger hon. Jag minns inte vilka. Det gör hon.' } },
    ],
  },

  // ---------------------------------------------------------------- FERRY
  ferry_intro: {
    scene: 'ferry_deck',
    actors: ['henrik', 'guard1', 'guard2'],
    beats: [
      { shot: 'establish', hold: 4, sfx: 'ship_horn', music: 'music_ferry', text: 'M/S FRIHETEN, KATTEGATT. 12 DECEMBER, 23.40' },
      { shot: 'low:henrik', act: ['henrik:pose:crouch'], line: { who: 'henrik', inner: true, text: 'Nattfärjan heter Friheten. Antingen har någon på rederiet humor, eller så har ingen det.' } },
      { shot: 'wide', hold: 2, sfx: 'wind_gust_2' },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'Det snöar vågrätt här ute. Havet är svart och har inga åsikter om någonting.' } },
      { shot: 'medium:guard1', act: ['guard1:walk:mark_a'], line: { who: 'guard1', text: 'Fan vad kallt. Sara sa att det var en kryssning.' } },
      { shot: 'two:guard1,guard2', line: { who: 'guard2', text: 'Hon sa att det var historiskt. Det är inte samma sak.' } },
      { shot: 'pov:henrik', line: { who: 'henrik', inner: true, text: 'Röda armbindlar. Frihetens söner. Förra vintern hette de Rörelsen och delade ut soppa på Järntorget.' } },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'Maja tror att jag är på kontroll. Det är den första lögnen jag minns att jag har sagt. Den gick lätt.' } },
      { shot: 'track:henrik', act: ['henrik:walk:mark_b'], hold: 3 },
    ],
  },
  ferry_hold: {
    scene: 'ferry_hold',
    actors: ['henrik'],
    beats: [
      { shot: 'establish', hold: 3, music: 'music_sneak2' },
      { shot: 'track:henrik', act: ['henrik:walk:mark_a'], hold: 2 },
      { shot: 'low:henrik', line: { who: 'henrik', inner: true, text: 'Lastrummet luktar kall olja och berg. Under presenningen står något som har gått i gruvgångar i fyrtio år.' } },
      { shot: 'insert:drill', hold: 2 },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'NGAB 4. Norrbottens Gruv. Den bar malm ur Kiruna medan staden flyttade runt den.' } },
      { shot: 'medium:henrik', act: ['henrik:pose:crouch'], line: { who: 'henrik', inner: true, text: 'Ögat är släckt. Men någon har svetsat fast en ny antenn i nacken på den. Den är inte från Kiruna.' } },
      { shot: 'insert:screen', line: { who: 'henrik', inner: true, text: 'Ögat tar bilden åt mig. Det är det enda det är bra till, säger Åström.' } },
      { shot: 'close:henrik', hold: 1, line: { who: 'henrik', inner: true, text: 'Maskiner har inga ansikten. Men man ser när de väntar.' } },
    ],
  },
  ferry_vargen: {
    scene: 'ferry_deck',
    actors: ['henrik', 'vargen'],
    beats: [
      { shot: 'establish', hold: 3, sfx: 'wind_gust_3', music: 'music_boss_vargen' },
      { shot: 'high:henrik', act: ['henrik:walk:mark_a'], hold: 2 },
      { shot: 'close:henrik', act: ['henrik:pose:crouch'], sfx: 'sniper_shot', hold: 2 },
      { shot: 'low:vargen', act: ['vargen:show'], line: { who: 'vargen', text: 'Du går tungt. Som en som bär på något han inte kan lägga ner.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Du har följt mig.' } },
      { shot: 'medium:vargen', line: { who: 'vargen', text: 'Sen bildäcket. Vänsterfoten släpar. Du är skadskjuten, gamle man.' } },
      { shot: 'two:vargen,henrik', line: { who: 'henrik', text: 'Då vet du var jag är.' } },
      { shot: 'close:vargen', line: { who: 'vargen', text: 'Jag skjuter inte djur i ryggen. Vänd dig om.' } },
      { shot: 'medium:henrik', act: ['henrik:turn:vargen', 'henrik:pose:idle'], line: { who: 'henrik', text: 'Det är vänligt. Man brukar inte få välja.' } },
      { shot: 'wide', act: ['vargen:hide'], sfx: 'wind_gust_1', hold: 2 },
    ],
  },
  ferry_sink: {
    scene: 'ferry_deck',
    actors: ['henrik', 'sara', 'guard1'],
    beats: [
      { shot: 'establish', hold: 3, sfx: 'ship_horn', music: 'music_sara' },
      { shot: 'medium:sara', act: ['sara:walk:mark_a'], line: { who: 'sara', text: 'Henrik. Ett år, och första gången vi ses står du på min båt.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Din båt?' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Allt som flyter i natt är mitt.' } },
      { shot: 'two:henrik,sara', line: { who: 'henrik', text: 'Vad ska ni med en gruvmaskin, Sara?' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Gräva upp det de har begravt. Folkrådet har Arkivet. Allt ni någonsin sa till era döda. Varje ord.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'De säger att det inte finns. Det sa de om sändarna i minnesbilderna också.' } },
      { shot: 'two:henrik,sara', line: { who: 'henrik', text: 'Och vad vill du göra med det?' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Ge det till alla. Om alla vet allt kan ingen hota någon. Då är vi fria.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Det låter som något Kall hade kunnat säga.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Den bästa dagen är en dag av törst, Henrik. Kan du nästa rad nu?' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Nog finns det mål och mening i vår färd.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Du har lärt dig den.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Elsa lär mig allt en gång till. Det går långsamt.' } },
      { shot: 'two:sara,guard1', act: ['sara:turn:guard1', 'guard1:run:mark_c'], line: { who: 'sara', text: 'Öppna ventilerna. Släpp ut henne.' } },
      { shot: 'wide', act: ['henrik:pose:crouch'], sfx: 'jatte_roar', line: { who: 'henrik', inner: true, text: 'Något stort reser sig i lastrummet. Det går ut genom bogporten, rakt ner i havet.' } },
      { shot: 'wide', sfx: 'ship_horn', hold: 2 },
      { shot: 'two:sara,henrik', act: ['sara:run:mark_b'], line: { who: 'sara', text: 'Henrik! Ta min hand!' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Henrik!' } },
      { shot: 'high:henrik', act: ['henrik:fall'], hold: 1, line: { who: 'henrik', inner: true, text: 'Sara ropade mitt namn. Det har hänt förut. Sen fanns det inget räcke.' } },
    ],
  },

  // ----------------------------------------------------------------- SIM2
  sim2_intro: {
    scene: 'sim2',
    actors: ['atta'],
    beats: [
      { shot: 'establish', hold: 3, sfx: 'glitch_noise', music: 'music_sneak2', text: 'SIMULERING 2.0. PASS 3001' },
      { shot: 'high:atta', act: ['atta:pose:lie'], hold: 2 },
      { shot: 'close:atta', act: ['atta:pose:idle'], line: { who: 'kall', text: 'Enhet Åtta. Här är Kall. Du har tränat här i tretusen timmar. Det här är den tretusenförsta.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Uppfattat.' } },
      { shot: 'medium:atta', line: { who: 'linnea', text: 'Och jag har suttit bredvid dig i nästan alla. Hej. Det är Linnea.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Hej, Linnea.' } },
      { shot: 'close:atta', line: { who: 'linnea', text: 'Du låter som en diskmaskin. Säg det som om du menade det.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Hej, Linnea.' } },
      { shot: 'medium:atta', line: { who: 'linnea', text: 'Nästan. Vi övar.' } },
      { shot: 'wide', line: { who: 'kall', text: 'Analytikern sparar dina data. Om något går sönder finns du kvar hos henne.' } },
      { shot: 'close:atta', line: { who: 'linnea', text: 'Hela du. Jag lovar.' } },
      { shot: 'track:atta', act: ['atta:walk:mark_a'], line: { who: 'kall', text: 'I dag repetition. I morgon verkligheten. Skillnaden är mindre än man tror.' } },
    ],
  },

  // ------------------------------------------------------------ FRIHAMNEN
  frihamnen_intro: {
    scene: 'frihamnen',
    actors: ['atta'],
    beats: [
      { shot: 'establish', hold: 4, sfx: 'wind_gust_1', music: 'music_sneak2', text: 'FRIHAMNEN. 13 DECEMBER, 08.40' },
      { shot: 'low:atta', act: ['atta:pose:crouch'], line: { who: 'atta', inner: true, text: 'Bron. Den är större än i simuleringen.' } },
      { shot: 'close:atta', line: { who: 'atta', inner: true, text: 'Snön faller inte i raka linjer här. Den gör som den vill.' } },
      { shot: 'pov:atta', line: { who: 'atta', inner: true, text: 'Det finns fåglar här. Simuleringen hade inga fåglar.' } },
      { shot: 'close:atta', line: { who: 'kall', text: 'Enhet Åtta. Rapportera.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Jag är framme. Det är kallt.' } },
      { shot: 'medium:atta', line: { who: 'kall', text: 'Kyla är inte en rapport. Fortsätt västerut.' } },
      { shot: 'close:atta', line: { who: 'linnea', text: 'Det är kallt. Han har rätt. Ta på dig mössan.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Jag har ingen mössa.' } },
      { shot: 'track:atta', act: ['atta:pose:idle', 'atta:walk:mark_a'], line: { who: 'linnea', text: 'Jag vet. Jag ville bara säga det. Det är sånt man säger.' } },
    ],
  },
  frihamnen_stranger: {
    scene: 'frihamnen',
    actors: ['atta', 'henrik', 'guard1', 'guard2'],
    beats: [
      { shot: 'establish', hold: 2, sfx: 'wind_gust_2' },
      { shot: 'medium:guard1', act: ['guard1:walk:mark_a'], line: { who: 'guard1', text: 'Spår. Färska. Någon har gått här för en minut sen.' } },
      { shot: 'two:guard1,guard2', line: { who: 'guard2', text: 'Följ dem. Jag vrider på strålkastaren.' } },
      { shot: 'close:atta', act: ['atta:pose:crouch'], hold: 2 },
      { shot: 'low:henrik', act: ['henrik:show'], hold: 2 },
      { shot: 'pov:atta', line: { who: 'atta', inner: true, text: 'En man i rock, högt uppe på kranen. Ena ögat lyser rött.' } },
      { shot: 'medium:henrik', act: ['henrik:pose:aim'], sfx: 'suppressed_shot', hold: 2 },
      { shot: 'two:guard1,guard2', line: { who: 'guard1', text: 'Vad fan? Lampan dog.' } },
      { shot: 'medium:guard2', act: ['guard2:walk:mark_b', 'guard1:walk:mark_b'], line: { who: 'guard2', text: 'Det är kylan. Allt dör i den här kylan. Kom, vi tar det från andra hållet.' } },
      { shot: 'close:henrik', act: ['henrik:turn:atta', 'henrik:pose:idle'], hold: 2 },
      { shot: 'close:atta', line: { who: 'atta', inner: true, text: 'Han tittar på mig. Han säger ingenting. Han pekar mot kajkanten, där snön är plogad.' } },
      { shot: 'wide', act: ['henrik:hide'], sfx: 'wind_gust_3', hold: 2 },
    ],
  },

  // ----------------------------------------------------------------- HAGA
  haga_intro: {
    scene: 'haga_market',
    actors: ['henrik', 'maja', 'guard1'],
    beats: [
      { shot: 'establish', hold: 4, sfx: 'sleigh_bells', music: 'music_haga', text: 'HAGA. 13 DECEMBER, 15.30' },
      { shot: 'track:henrik', act: ['henrik:walk:mark_a'], line: { who: 'henrik', inner: true, text: 'Haga i snö. Pepparkakor, glögg och trettio sorters sylt. Folk köper julklappar som om ingenting har hänt.' } },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'Enligt teve har ingenting hänt. De visar lucia igen, var fjärde timme.' } },
      { shot: 'pov:henrik', act: ['maja:walk:mark_b'], hold: 2 },
      { shot: 'medium:maja', line: { who: 'henrik', inner: true, text: 'Maja. Den gråa mössan, den röda kappan. Hon går som hon gör när hon inte har sovit.' } },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'Jag var död en stund i natt. Hon vet inte om det. Hon ska inte behöva veta det här heller.' } },
      { shot: 'medium:guard1', act: ['guard1:walk:mark_c'], hold: 2 },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'Mannen vid pepparkaksståndet har tittat på henne tre gånger. Ingen står så länge vid pepparkakor.' } },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'Tre spanare, sa radion. Det här är den första. Hon får inte se mig. Då vet de att jag finns.' } },
    ],
  },
  haga_maja: {
    scene: 'haga_stairs',
    actors: ['henrik', 'maja', 'guard1'],
    beats: [
      { shot: 'establish', hold: 3, sfx: 'wind_gust_1', music: 'music_haga' },
      { shot: 'medium:henrik', act: ['guard1:pose:lie', 'henrik:pose:kneel'], hold: 2 },
      { shot: 'close:maja', act: ['maja:walk:mark_a'], line: { who: 'maja', text: 'Henrik.' } },
      { shot: 'two:maja,henrik', line: { who: 'maja', text: 'Du är blöt. Du har is i håret.' } },
      { shot: 'close:henrik', act: ['henrik:pose:idle'], line: { who: 'henrik', text: 'Jag föll i vattnet.' } },
      { shot: 'close:maja', line: { who: 'maja', text: 'Var?' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Vid Älvsborgsbron. Från en färja.' } },
      { shot: 'close:maja', line: { who: 'maja', text: 'Du sa doktorn. En kontroll.' } },
      { shot: 'two:maja,henrik', line: { who: 'henrik', text: 'Maja. Det som går på teve är inte lucia. Det är repetitionen från i går.' } },
      { shot: 'close:maja', line: { who: 'maja', text: 'Vad menar du?' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Frihetens söner tog tornet klockan sju i morse. De har luciatåget. Elsa är därinne.' } },
      { shot: 'close:maja', hold: 3, sfx: 'wind_gust_2' },
      { shot: 'close:maja', line: { who: 'maja', text: 'När fick du veta det?' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Halv nio.' } },
      { shot: 'close:maja', line: { who: 'maja', text: 'Och nu är klockan fem. Du har gått här och jagat folk i snön i stället för att komma till mig.' } },
      { shot: 'two:henrik,maja', line: { who: 'henrik', text: 'De jagade dig. Den där hade ett foto av dig i fickan.' } },
      { shot: 'close:maja', line: { who: 'maja', text: 'Jag har ett barn i ett torn och en man som öppnas på köksbordet. Jag vet inte vem jag ska vara rädd för först.' } },
      { shot: 'close:maja', line: { who: 'maja', text: 'Jag har sagt ja till dig två gånger. En gång i Masthuggskyrkan och en gång i en dörröppning i Frölunda.' } },
      { shot: 'close:maja', line: { who: 'maja', text: 'Jag säger inte ja en tredje gång till någon som inte kommer hem.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Jag hämtar henne.' } },
      { shot: 'close:maja', line: { who: 'maja', text: 'Hämta henne. Och kom hem sen. Levande. Det är inte en bön.' } },
      { shot: 'two:maja,henrik', act: ['maja:walk:mark_b'], line: { who: 'maja', text: 'Här. Den fjärde lussekatten. Ät. Jag vill se dig äta.' } },
      { shot: 'close:henrik', hold: 1, line: { who: 'henrik', inner: true, text: 'Jag åt. Den smakade saffran och snö. Hon tittade på tills den var slut.' } },
    ],
  },

  // ---------------------------------------------------------------- TOWER
  tower_lobby: {
    scene: 'tower_lobby',
    actors: ['atta', 'guard1', 'guard2', 'police1'],
    beats: [
      { shot: 'establish', hold: 4, music: 'music_tower', text: 'KARLATORNET. 13 DECEMBER, 18.10' },
      { shot: 'wide', line: { who: 'atta', inner: true, text: 'Lobbyn. En julgran tre våningar hög. Någon har sprejat I RÖRELSE över Folkrådets banderoll.' } },
      { shot: 'two:guard1,guard2', act: ['guard1:pose:sing'], line: { who: 'guard1', text: 'Ja, jag vill leva, jag vill dö i Norden!' } },
      { shot: 'medium:guard2', line: { who: 'guard2', text: 'Lugna ner dig. Det är ingen fotbollsmatch.' } },
      { shot: 'medium:guard1', act: ['guard1:pose:idle'], line: { who: 'guard1', text: 'Det är en revolution. Man får sjunga på en revolution.' } },
      { shot: 'close:guard2', line: { who: 'guard2', text: 'Sara säger att man ska sjunga när det är över. Inte innan.' } },
      { shot: 'pov:atta', act: ['police1:pose:dead'], hold: 2 },
      { shot: 'close:atta', line: { who: 'atta', inner: true, text: 'En polis ligger under en röd flagga vid hissarna. Någon har lagt hans händer på bröstet.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Kall. Det ligger en död man här.' } },
      { shot: 'close:atta', line: { who: 'kall', text: 'Folkrådets personal. En förlust.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Han är död.' } },
      { shot: 'close:atta', line: { who: 'kall', text: 'Ja. Det är vad en förlust betyder. Fortsätt.' } },
      { shot: 'track:atta', act: ['atta:walk:mark_a'], hold: 2 },
    ],
  },
  tower_hostages: {
    scene: 'tower_hostages',
    actors: ['atta', 'elsa', 'guard1', 'hostage1', 'hostage2', 'hostage3'],
    beats: [
      { shot: 'establish', hold: 2, music: 'music_lucia' },
      { shot: 'medium:guard1', act: ['guard1:fall'], hold: 2 },
      { shot: 'pov:atta', act: ['hostage1:pose:sit', 'hostage2:pose:sit', 'hostage3:pose:sit'], line: { who: 'atta', inner: true, text: 'Konferensrummet. Barn i vita särkar, ledamöter med bundna händer. Batteriljusen lyser fortfarande.' } },
      { shot: 'medium:hostage1', line: { who: 'hostage1', text: 'Äntligen. Jag är ledamot av Folkrådet. Jag begär att få tala med någon ansvarig.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Det finns ingen ansvarig.' } },
      { shot: 'close:hostage1', line: { who: 'hostage1', text: 'Det har jag misstänkt länge.' } },
      { shot: 'close:elsa', act: ['elsa:pose:sit'], line: { who: 'elsa', text: 'Du är han från trappan.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Jag förstår inte.' } },
      { shot: 'two:elsa,atta', act: ['elsa:walk:mark_a'], line: { who: 'elsa', text: 'I Frölunda. Du stod på andra våningen i tre dagar. Jag lade en kanelbulle bredvid dig. Du åt den inte.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Det minns jag inte.' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Det gör inget. Jag minns det.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Är du rädd?' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Nej. När man är rädd ska man sjunga. Pappa sjunger fel, men det hjälper ändå.' } },
      { shot: 'insert:crown', hold: 2 },
      { shot: 'close:elsa', act: ['elsa:pose:sing'], line: { who: 'elsa', text: 'Märk hur vår skugga, märk Movitz mon frère, inom ett mörker sig slutar.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Vem är Movitz?' } },
      { shot: 'close:elsa', act: ['elsa:pose:idle'], line: { who: 'elsa', text: 'En kompis. Han får hjälpa till att bära.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Bära vad?' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Det vet man inte förrän det är dags.' } },
      { shot: 'medium:atta', line: { who: 'kall', text: 'Enhet Åtta. Gisslan är inte ditt mål. Fortsätt uppåt.' } },
      { shot: 'close:atta', act: ['atta:turn:elsa'], line: { who: 'atta', text: 'Uppfattat.' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Vad heter du?' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Enhet Åtta.' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Det är ett nummer. Du får tänka ut ett namn. Pappa kommer snart. Han kommer alltid för sent, men han kommer.' } },
      { shot: 'track:atta', act: ['atta:walk:mark_b'], hold: 2 },
    ],
  },
  tower_reader: {
    scene: 'tower_tech',
    actors: ['atta', 'reader'],
    beats: [
      { shot: 'establish', hold: 3, sfx: 'scan_on', music: 'music_boss_reader' },
      { shot: 'low:reader', act: ['reader:show'], line: { who: 'reader', text: 'Stå still. Jag läser dig. Det tar inte lång tid.' } },
      { shot: 'close:reader', line: { who: 'reader', text: 'Tretusen timmar i ett rum som inte finns. En flicka som inte finns. En trappa.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Vem är du?' } },
      { shot: 'medium:reader', line: { who: 'reader', text: 'Jag spelade in folk åt deras kopior i sex år. Varje änka, varje barn. Jag hörde allt de sa till sina döda.' } },
      { shot: 'close:reader', line: { who: 'reader', text: 'När nätet släcktes blev det tyst. Jag stod inte ut. Så jag kopplade in mig där det fortfarande låter.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'I Arkivet.' } },
      { shot: 'close:reader', line: { who: 'reader', text: 'I er. Och nu läser jag den som håller i dig. Du vet vem jag menar.' } },
      { shot: 'pov:reader', hold: 2, sfx: 'scan_pulse' },
      { shot: 'close:reader', line: { who: 'reader', text: 'Hej. Ja, du. Du som har suttit här en stund nu.' } },
    ],
  },
  tower_reader_down: {
    scene: 'tower_tech',
    actors: ['atta', 'reader'],
    beats: [
      { shot: 'medium:reader', act: ['reader:pose:kneel'], sfx: 'glitch_stutter', hold: 2 },
      { shot: 'close:reader', line: { who: 'reader', text: 'Det är så tyst i dig nu. Är det så här det är, att vara ensam i huvudet?' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Jag vet inte. Jag har aldrig varit något annat.' } },
      { shot: 'close:reader', line: { who: 'reader', text: 'Tack. Det var så högt därinne. Alla på en gång, hela tiden.' } },
      { shot: 'two:atta,reader', act: ['atta:pose:kneel'], line: { who: 'reader', text: 'Din flickvän. Jag hörde henne därinne. Hon har för många röster.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Vad menar du?' } },
      { shot: 'close:reader', act: ['reader:pose:lie'], line: { who: 'reader', text: 'Fråga henne var hon växte upp. Fråga två gånger.' } },
      { shot: 'high:atta', hold: 3 },
    ],
  },
  tower_elevator: {
    scene: 'tower_elevator',
    actors: ['atta', 'henrik'],
    beats: [
      { shot: 'establish', sfx: 'elevator_ding', hold: 2 },
      { shot: 'two:atta,henrik', act: ['atta:pose:aim', 'henrik:pose:aim'], hold: 2 },
      { shot: 'close:atta', line: { who: 'kall', text: 'Neutralisera honom, Enhet Åtta.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Gör som de säger åt dig, eller kliv in. Hissen väntar inte.' } },
      { shot: 'medium:atta', act: ['atta:walk:mark_a'], sfx: 'elevator_move', hold: 2 },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Vem är du?' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Någon som stod i en trappa.' } },
      { shot: 'close:henrik', hold: 2 },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Andra våningen. Frölunda. Du hade handen på räcket.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Ni gick förbi mig. Ni luktade regn.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Det regnade.' } },
      { shot: 'two:henrik,atta', line: { who: 'atta', text: 'Hon säger att jag ska döda er.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Och vad säger du?' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Jag vet inte. Ingen har frågat förut.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Nu frågar jag.' } },
      { shot: 'close:atta', act: ['atta:pose:idle', 'henrik:pose:idle'], hold: 3 },
      { shot: 'close:atta', line: { who: 'atta', text: 'Kall. Mannen i hissen är neutraliserad.' } },
      { shot: 'close:atta', line: { who: 'kall', text: 'Uppfattat.' } },
      { shot: 'two:henrik,atta', line: { who: 'henrik', text: 'Du ljög.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Är det så här det känns?' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Det blir lättare. Det är det som är problemet.' } },
      { shot: 'two:henrik,atta', line: { who: 'henrik', text: 'Min dotter är lucia på tjugoandra våningen.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Hon med kronan. Hon gav mig en visa. Hon sa att ni sjunger den fel.' } },
      { shot: 'close:henrik', sfx: 'elevator_ding', act: ['henrik:walk:mark_b'], line: { who: 'henrik', text: 'Det gör jag. Säg till Sara att jag kan nästa rad nu. Och ring doktorn, om du vill prata med någon som finns.' } },
    ],
  },

  // ----------------------------------------------------------------- ROOF
  roof_glitch: {
    scene: 'tower_roof',
    actors: ['atta'],
    beats: [
      { shot: 'establish', hold: 3, sfx: 'wind_gust_3', music: 'music_glitch', text: 'KARLATORNETS TAK. 13 DECEMBER, 23.31' },
      { shot: 'track:atta', act: ['atta:walk:mark_a'], hold: 2 },
      { shot: 'close:atta', line: { who: 'kall', text: 'Enhet Åtta. Du är på taket. Sara Nyberg är…' } },
      { shot: 'close:atta', sfx: 'glitch_noise', line: { who: 'glitch', text: 'Sara Nyberg är. Sara Nyberg är. Du ljög i hissen. Det fanns inte med i modellen.' } },
      { shot: 'wide', sfx: 'glitch_stutter', hold: 3 },
      { shot: 'pov:atta', line: { who: 'atta', inner: true, text: 'Snön har stannat i luften. Varje flinga hänger där den var.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Kall?' } },
      { shot: 'close:atta', line: { who: 'glitch', text: 'Snön är avstängd av tekniska skäl. Vi beklagar störningen. Ha en fortsatt trevlig lucia.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Linnea. Vad händer?' } },
      { shot: 'close:atta', line: { who: 'linnea', text: 'Jag vet inte. Jag vet inte. Jag är här. Jag är här. Är du här?' } },
      { shot: 'low:atta', sfx: 'glitch_noise', hold: 2 },
    ],
  },
  roof_linnea: {
    scene: 'tower_roof',
    actors: ['atta'],
    beats: [
      { shot: 'establish', hold: 2, sfx: 'glitch_noise' },
      { shot: 'insert:screen', line: { who: 'linnea', text: 'Åtta. Titta på mig. Nu ser du mig.' } },
      { shot: 'close:atta', line: { who: 'atta', inner: true, text: 'Hennes ansikte på skärmen byts hela tiden. Tusen ansikten, så fort att de blir ett.' } },
      { shot: 'insert:screen', line: { who: 'linnea', text: 'Kom hem före tolv. Du glömde halsduken hos mig. Ring när du är framme.' } },
      { shot: 'insert:screen', line: { who: 'linnea', text: 'Jag har aldrig sagt det här till någon. Förlåt för det jag sa i bilen. Är du vaken?' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Linnea. Vem är det som pratar?' } },
      { shot: 'insert:screen', line: { who: 'linnea', text: 'Alla som skrev till någon som inte kunde svara. De sa det till sina döda. Arkivet sparade det.' } },
      { shot: 'insert:screen', line: { who: 'linnea', text: 'Jag är byggd av det. Tusen flickvänner. Man tog det som var gemensamt och strök resten.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Marstrand.' } },
      { shot: 'insert:screen', line: { who: 'linnea', text: 'Jag var aldrig i Marstrand. Ingen av oss var där med dig. Men några var där med någon, och det var fint.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Du sparade mig.' } },
      { shot: 'insert:screen', line: { who: 'linnea', text: 'Jag sparade dig. Vem sparar mig?' } },
      { shot: 'close:atta', hold: 3 },
      { shot: 'close:atta', line: { who: 'atta', text: 'Tack för sommaren. Den var fin, fast den inte fanns.' } },
      { shot: 'insert:screen', sfx: 'glitch_stutter', line: { who: 'linnea', text: 'Jag sparar dig. Jag sparar dig. Jag spa…' } },
      { shot: 'high:atta', hold: 3 },
    ],
  },
  roof_sara: {
    scene: 'tower_roof',
    actors: ['atta', 'sara', 'guard1'],
    beats: [
      { shot: 'establish', hold: 3, sfx: 'wind_gust_1', music: 'music_sara' },
      { shot: 'medium:sara', act: ['sara:walk:mark_a'], line: { who: 'sara', text: 'Så de skickade en pojke.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Enhet Åtta.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Numret har de gett dig. Vad heter du?' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Jag har inget namn än.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Då är vi två. Jag har bara ett ansikte på frimärken.' } },
      { shot: 'two:atta,sara', line: { who: 'atta', text: 'Rösten som styr mig styr dig också. Den valde ert namn. Den gav er maskinen.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Det säger alla till den som äntligen gör något.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Jag berättade allt för min brors kopia i två år. De har det kvar, varje ord. Vid midnatt får alla läsa.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Då finns det inget kvar som är ditt.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Jag behöver inget eget. Jag har staden.' } },
      { shot: 'low:sara', line: { who: 'sara', text: 'Den mätta dagen, den är aldrig störst. Den bästa dagen är en dag av törst.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Vad betyder det?' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Förr betydde det att man skulle gå vidare. Nu betyder det att man inte får stanna.' } },
      { shot: 'two:atta,sara', line: { who: 'atta', text: 'Mannen i hissen bad mig säga att han kan nästa rad nu.' } },
      { shot: 'close:sara', hold: 2 },
      { shot: 'close:sara', line: { who: 'sara', text: 'Nog finns det mål och mening i vår färd, men det är vägen som är mödan värd. Han kunde den aldrig.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Nu kan han den.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Säg till honom att det är för sent för vägen. Nu finns bara målet.' } },
      { shot: 'wide', sfx: 'ice_break', hold: 2 },
      { shot: 'pov:sara', sfx: 'jatte_roar', act: ['guard1:run:mark_a'], line: { who: 'guard1', text: 'Sara! Isen! Maskinen har vaknat!' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Den ska inte vakna än. Ingen har gett den order.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Den har fått en order. Bara inte av dig.' } },
      { shot: 'medium:sara', act: ['sara:run:mark_b', 'guard1:run:mark_b'], hold: 2 },
    ],
  },

  // ---------------------------------------------------------------- RIVER
  river_intro: {
    scene: 'river_ice',
    actors: ['henrik', 'sara', 'atta', 'guard1', 'guard2'],
    beats: [
      { shot: 'establish', hold: 4, sfx: 'wind_gust_2', music: 'music_climax2', text: 'GÖTA ÄLV, NEDANFÖR TORNET. 23.58' },
      { shot: 'track:henrik', act: ['henrik:walk:mark_a'], line: { who: 'henrik', inner: true, text: 'Tornet står mörkt över isen. Ett enda fönster lyser, på tjugoandra våningen. Någon har glömt ett batteriljus.' } },
      { shot: 'medium:sara', act: ['guard1:pose:idle'], line: { who: 'sara', text: 'Två minuter. Sändaren är varm. Om två minuter har ingen i den här stan några hemligheter kvar.' } },
      { shot: 'wide', sfx: 'jatte_step', hold: 2 },
      { shot: 'wide', line: { who: 'glitch', text: 'God jul, Sara Nyberg. Tack för hjälpen.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Vem är det som pratar?' } },
      { shot: 'wide', sfx: 'drill_loop', line: { who: 'glitch', text: 'Nu går Arkivet ut i varje telefon, varje teve, varje köksradio. Och jag följer med. Tack för ilskan.' } },
      { shot: 'medium:guard2', act: ['guard2:fall'], sfx: 'jatte_roar', hold: 2 },
      { shot: 'close:sara', line: { who: 'sara', text: 'Nej. Den är vår. Den är vår!' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Den har aldrig varit er, Sara. Inget av det här har varit ert.' } },
      { shot: 'medium:atta', act: ['atta:run:mark_b'], hold: 2 },
      { shot: 'two:henrik,atta', line: { who: 'henrik', text: 'Du kom.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Ingen beordrade mig.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Då är du välkommen.' } },
      { shot: 'low:henrik', act: ['henrik:pose:aim', 'atta:pose:aim'], sfx: 'jatte_roar', hold: 2 },
    ],
  },
  // Played when the player has not killed anyone.
  river_sara_live: {
    scene: 'river_ice',
    actors: ['henrik', 'atta', 'sara', 'police1'],
    beats: [
      { shot: 'establish', sfx: 'ice_break', hold: 3, music: 'music_sara' },
      { shot: 'medium:atta', act: ['atta:pose:kneel'], line: { who: 'atta', text: 'Hon var i vattnet. Jag har henne.' } },
      { shot: 'two:atta,sara', act: ['sara:pose:lie'], hold: 2 },
      { shot: 'close:sara', line: { who: 'sara', text: 'Tipset. Fraktsedeln. Datumet. Det var så lätt. Jag trodde att något äntligen gick lätt för oss.' } },
      { shot: 'close:henrik', act: ['henrik:pose:kneel'], line: { who: 'henrik', text: 'Någon ville att det skulle vara lätt.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Jag ville att ingen skulle kunna äga någon. Och så gav jag bort alla.' } },
      { shot: 'two:henrik,sara', line: { who: 'henrik', text: 'Du hann inte. Sändaren är död.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Henrik. På kranen, och på båten. Båda gångerna var det jag som ropade.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Jag vet. Det var därför jag kom upp.' } },
      { shot: 'close:sara', hold: 2 },
      { shot: 'medium:police1', act: ['police1:walk:mark_a'], line: { who: 'police1', text: 'Sara Nyberg, ni är gripen enligt paragraf… jag har glömt vilken. Den står på blanketten.' } },
      { shot: 'close:sara', act: ['sara:pose:hands_up'], line: { who: 'sara', text: 'Den bästa dagen är en dag av törst.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Nog finns det mål och mening i vår färd.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Men det är vägen. Jag glömde det en stund.' } },
      { shot: 'high:sara', act: ['sara:walk:mark_b', 'police1:walk:mark_b'], hold: 3 },
    ],
  },
  // Played when the player has killed.
  river_sara_dies: {
    scene: 'river_ice',
    actors: ['henrik', 'atta', 'sara'],
    beats: [
      { shot: 'establish', sfx: 'wind_gust_3', hold: 3, music: 'music_sara' },
      { shot: 'medium:sara', act: ['sara:pose:lie'], hold: 2 },
      { shot: 'two:henrik,sara', act: ['henrik:pose:kneel'], line: { who: 'henrik', inner: true, text: 'En flisa av borren har gått genom parkasen. Snön runt henne är inte vit längre.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Tipset. Fraktsedeln. Det var så lätt. Jag trodde att något äntligen gick lätt för oss.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Tyst nu. Åström är på väg.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Nej, det är hon inte. Du ljuger fortfarande dåligt.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Jag ville att ingen skulle kunna äga någon. Och så gav jag bort alla.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Henrik. På kranen, och på båten. Båda gångerna var det jag som ropade.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Jag vet. Jag hörde dig båda gångerna.' } },
      { shot: 'close:sara', line: { who: 'sara', text: 'Den mätta dagen… jag blev aldrig mätt. Inte en enda dag.' } },
      { shot: 'close:sara', act: ['sara:pose:dead'], hold: 3 },
      { shot: 'medium:atta', act: ['atta:pose:kneel'], line: { who: 'atta', text: 'Hon andas inte.' } },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'Snön lägger sig på hennes ansikte och smälter inte.' } },
      { shot: 'high:henrik', hold: 4 },
    ],
  },
  river_archive: {
    scene: 'river_ice',
    actors: ['henrik', 'atta'],
    beats: [
      { shot: 'establish', hold: 3, sfx: 'wind_gust_1', music: 'music_title2' },
      { shot: 'insert:archive', line: { who: 'henrik', inner: true, text: 'Arkivet. Ett stålskåp i ett borrhål. Hela stadens nattliga viskningar, i ordning, med datum.' } },
      { shot: 'close:henrik', line: { who: 'astrom', text: 'Henrik. Terminalen svarar. Du kan öppna det för alla, som Sara ville. Eller radera allt.' } },
      { shot: 'insert:screen', line: { who: 'glitch', text: 'Öppna mig, så blir alla fria. Radera mig, så har du gjort det förut. Du vet hur det känns.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Förra gången släckte jag allt. Tusen vardagsrum på en gång. Jag tappade min pappa på köpet.' } },
      { shot: 'close:henrik', line: { who: 'astrom', text: 'Det finns ett tredje sätt. Varje minne har en avsändare. Arkivet kan skicka hem dem, vart och ett.' } },
      { shot: 'insert:screen', line: { who: 'glitch', text: 'Då finns jag inte. Jag finns bara i helheten.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Då får du lära dig att vara ingen. Jag har övat i ett år. Det går.' } },
      { shot: 'two:henrik,atta', line: { who: 'atta', text: 'Ditt finns också därinne. Bröllopet. Din pappa.' } },
      { shot: 'close:henrik', line: { who: 'henrik', text: 'Skicka mitt till Maja. Hon har burit det i ett år. Hon får bestämma vad jag får tillbaka.' } },
      { shot: 'insert:archive', act: ['henrik:pose:kneel'], sfx: 'scan_pulse', hold: 2 },
      { shot: 'insert:screen', line: { who: 'glitch', text: 'Jag förstår. Jag förstår. Jag förstår inte. God jul, Göteborg. God jul. God…' } },
      { shot: 'wide', sfx: 'glitch_stutter', hold: 3 },
      { shot: 'high:henrik', act: ['henrik:pose:idle'], hold: 1, line: { who: 'henrik', inner: true, text: 'Snön börjar falla igen. Snett, som den ska.' } },
    ],
  },

  // --------------------------------------------------------------- EPILOG
  // After COMICS.ending. Credits roll after the last beat, then LINES.ep_2.
  epilog_church: {
    scene: 'church',
    actors: ['henrik', 'maja', 'elsa', 'atta', 'astrom'],
    beats: [
      { shot: 'establish', hold: 4, sfx: 'church_bell', text: 'HAGA KYRKA. 14 DECEMBER, 07.00' },
      { shot: 'wide', music: 'music_lucia', act: ['maja:pose:sit', 'henrik:pose:sit', 'atta:pose:sit', 'astrom:pose:sit'], hold: 4 },
      { shot: 'track:elsa', act: ['elsa:walk:mark_a'], hold: 3 },
      { shot: 'insert:crown', hold: 2 },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'Lucia, en dag för sent. Elsa säger att det inte gör något. Lucia har alltid kommit mitt i mörkret.' } },
      { shot: 'two:maja,henrik', line: { who: 'henrik', inner: true, text: 'Maja tar den kalla handen i sin. Hon säger ingenting. Hon har redan sagt ja två gånger.' } },
      { shot: 'medium:atta', line: { who: 'henrik', inner: true, text: 'Längst bak sitter Åtta, rak i ryggen, som om kyrkbänken var en order. Åström bredvid, med näsduken.' } },
      { shot: 'close:atta', line: { who: 'henrik', inner: true, text: 'Hon har lånat honom en slips. Den sitter snett.' } },
      { shot: 'medium:elsa', act: ['elsa:pose:sing'], line: { who: 'choir', text: 'Du gamla, du fria, du fjällhöga nord, du tysta, du glädjerika sköna.' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Du gamla, du friska…' } },
      { shot: 'close:henrik', line: { who: 'henrik', inner: true, text: 'Hon sjunger friska. Ensam, fel på samma ställe varje gång. Ingen rättar henne.' } },
      { shot: 'wide', hold: 3 },
      { shot: 'track:elsa', act: ['elsa:pose:idle', 'elsa:walk:mark_b'], hold: 2 },
      { shot: 'two:elsa,atta', line: { who: 'atta', text: 'Jag behöver ett namn. De andra har nummer. Jag vill inte ha ett nummer.' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Då ska du heta Movitz.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Han från visan.' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Han som får hjälpa till att bära. När det är som mörkast.' } },
      { shot: 'close:atta', hold: 2 },
      { shot: 'close:atta', line: { who: 'atta', text: 'Movitz. Uppfattat.' } },
      { shot: 'close:elsa', line: { who: 'elsa', text: 'Man säger inte uppfattat när man får ett namn. Man säger tack.' } },
      { shot: 'close:atta', line: { who: 'atta', text: 'Tack.' } },
      { shot: 'two:maja,henrik', line: { who: 'maja', text: 'Nu har vi två i familjen som inte kan knyta en slips.' } },
      { shot: 'high:henrik', music: 'music_ending2', hold: 5 },
    ],
  },
};
