// Voice-over playback. Clips are generated by tools/voice (one Opus file per
// line) and listed in assets/voice/index.json with their durations. Any line
// without a clip simply stays silent, so the game never depends on them.

import { audio } from './audio.js';

const INDEX_URL = `${import.meta.env.BASE_URL}assets/voice/index.json`;
const MUSIC_DUCK = 0.45;

class VoicePlayer {
  constructor() {
    this.index = {};
    this.current = null;
  }

  async init() {
    try {
      const r = await fetch(INDEX_URL);
      this.index = r.ok ? await r.json() : {};
    } catch {
      this.index = {};
    }
  }

  /** True when the line has a clip and audio is running. */
  has(id) { return !!id && !!this.index[id] && !!audio.ctx; }

  /** Clip length in seconds (0 when unvoiced). */
  duration(id) { return this.has(id) ? this.index[id] : 0; }

  preload(ids) {
    for (const id of ids) if (this.has(id)) audio.load(`voice/${id}`);
  }

  /**
   * Play a line, cutting off whatever is speaking. `onEnd` runs when the clip
   * finishes on its own (not when it is interrupted). Returns false if unvoiced.
   */
  play(id, { radio = false, onEnd = null } = {}) {
    this.stop();
    if (!this.has(id)) return false;
    const token = {};
    this.current = token;
    audio.setDuck(MUSIC_DUCK);
    token.handle = audio.play(`voice/${id}`, {
      bus: radio ? 'radio' : 'voice',
      onEnd: () => {
        if (this.current !== token) return;
        this.current = null;
        audio.setDuck(1);
        onEnd?.();
      },
    });
    return true;
  }

  stop() {
    if (!this.current) return;
    this.current.handle?.stop(0.08);
    this.current = null;
    audio.setDuck(1);
  }

  get speaking() { return !!this.current; }
}

export const voice = new VoicePlayer();
